name: wasalny
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  floating_bottom_navigation_bar: ^1.5.2
  google_maps_flutter: ^2.2.5
  flutter_polyline_points: ^1.0.0
  cloud_firestore: ^4.4.3
  firebase_core: ^2.5.0
  firebase_database: ^10.0.10
  intl: 0.17.0
  location: ^4.2.0
  provider: ^6.0.5
  font_awesome_flutter: ^10.4.0
  awesome_dialog: ^3.0.2
  firebase_auth: ^4.5.0
  fluttertoast: ^8.2.1
  url_launcher: ^6.1.11
  dio: ^5.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/images/uniBusIcon.png"
  adaptive_icon_background: "#040C4D"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/PinBus.png
    - assets/images/CoinDollar.png
    - assets/images/MainPageBus1.png
    - assets/images/MainPageBus2.png
    - assets/images/star.png
    - assets/images/UserProfile.png
    - assets/images/WhiteCreditCard.png
    - assets/images/WelcomePageBus.png
    - assets/images/OrangeLeatherWallet.png
    - assets/images/mobile-app.png
    - assets/images/PinLine.png
    - assets/images/2pins.png


    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
#    - fonts:
#      - family: Poppins
#        fonts:
#          - asset: assets/fonts/Poppins-Regular.ttf
#          - asset: assets/fonts/Poppins-Bold.ttf
#            weight: 700

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
